# Site Info
title: Study Log
tagline: 'Development Log'
description: 'A Jekyll theme adapted from <a href="http://lanyon.getpoole.com/" target="_blank">Lanyon</a>. Made by <a href="http://codinfox.github.io" target="_blank">@codinfox</a>.'
baseurl: ""
url: http://just4study.github.io
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 6
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: Just4study
  description: <strong>Just4Study</strong> (Young-Uk)<br>This is My <strong>Study Log</strong>
  gravatar: 3c2986ad7ac1f2230ea3596f44563328 # md5 hash of your email address
  contact:
    linkedin:  https://www.linkedin.com/in/lizhihao
    github:    https://github.com/just4study
    email:     http://www.google.com/recaptcha/mailhide/d?k=01I3lZFiZYng9N3QxYEtsDaQ==&c=31wAnZkuKqcG0ATAqJN8Z3ln5kkYLA9TwkGc-IbygpM=

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  DevLog:           
    - '/blog/'
    - { Archive: '/blog/archiv/'}
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:          
    - '/about/'
  My Github: 
    - 'http://github.com/just4study'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

thumbnail:
  image: /public/img/thumbnail.jpg
  caption: LA Griffith Park Photo By &copy; Just4Study

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-00000000-1' # leave blank if you don't want google analytics
disqus_short_name: 'just4study' # leave blank if you don't want disqus

